/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BeliefsRouteImport } from './routes/beliefs'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as WorshipRouteImport } from './routes/worship'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BeliefsRoute = BeliefsRouteImport.update({
  id: '/beliefs',
  path: '/beliefs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipRoute = WorshipRouteImport.update({
  id: '/worship',
  path: '/worship',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beliefs': typeof BeliefsRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/worship': typeof WorshipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beliefs': typeof BeliefsRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/worship': typeof WorshipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beliefs': typeof BeliefsRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/worship': typeof WorshipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/beliefs' | '/community' | '/contact' | '/worship'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/beliefs' | '/community' | '/contact' | '/worship'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/beliefs'
    | '/community'
    | '/contact'
    | '/worship'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeliefsRoute: typeof BeliefsRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  WorshipRoute: typeof WorshipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beliefs': {
      id: '/beliefs'
      path: '/beliefs'
      fullPath: '/beliefs'
      preLoaderRoute: typeof BeliefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship': {
      id: '/worship'
      path: '/worship'
      fullPath: '/worship'
      preLoaderRoute: typeof WorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeliefsRoute: BeliefsRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  WorshipRoute: WorshipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
